### ISSUE TITLE
Promotion competition! ($6,000 in prizes!) 

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/foundry-full-course-f23#10]
# $6,000 Prize pool

I will budget $5,000 to the top 20 promotions of this course ($250 in ETH each!). 

## And a grand prize of $1,000 for the best piece of marketing material! 

The goal of this is to get developers up to speed on web3. If we are going to get web3 to retail, we need more developers like yourself taking courses like this. So this is your chance to join the fight and make some dope content! 

# To enter

0. Wait till the course launches. All entries posted here before the Video is up are disqualified. 

1. Comment on this issue with a link to your
- TikTok / YouTube shorts
- Twitter Threads
- LinkedIn posts
- YouTube videos
- Blogs
- Meme on Reddit
- Other

2. In the media (not the comment on this issue), you must include an ARBITRUM address, which I will send at the end of the Judging period. (Sometime in July or August). 

3. I will NOT send money to smart contract-based accounts (It MUST be an EOA).  

4. This issue will be closed July 6th, 2023. That will be the last day to post! 

# To claim your prize 

I will send the payments after the judging period in ETH on ARBITRUM. I will not be responsible for it you mess up sending the address. Sorry. 

# Judging 

July 6th 2023 I'll start judging, and I will award prizes to the following different categories:
1. Most reach 
2. How funny it is 
3. How many web2 developers take the course based off your content
5. How good the SEO is
6. How creative it is

An entry can only win on one of the categories. 

I will give out at least 2 awards to each of the following mediums:
- TikTok / YouTube shorts
- Twitter Threads
- LinkedIn posts
- YouTube videos
- Blogs
- Meme on Reddit
- Something else

So yes, if you have a banger tweet, that's eligible. 

Sadly, I don't have time to coordinate a DAO around this, so judging will be 100% my discretion. If you don't like my judging, too bad 😜

**Comment by PatrickAlphaC** [comment]
# $5,000 Prize pool

I will budget $5,000 to the top 20 promotions of this course ($250 in ETH each!). 

The goal of this is to get developers up to speed on web3. If we are going to get web3 to retail, we need more developers like yourself taking courses like this. So this is your chance to join the fight and make some dope content! 

# To enter

0. Wait till the course launches. All entries posted here before the Video is up are disqualified. 

1. Comment on this issue with a link to your
- TikTok / YouTube shorts
- Twitter Threads
- LinkedIn posts
- YouTube videos
- Blogs
- Meme on Reddit
- Other

2. In the media (not the comment on this issue), you must include an ARBITRUM address, which I will send at the end of the Judging period. (Sometime in July or August). 

3. I will NOT send money to smart contract-based accounts (It MUST be an EOA).  

4. This issue will be closed July 6th, 2023. That will be the last day to post! 

# To claim your prize 

I will send the payments after the judging period in ETH on ARBITRUM. I will not be responsible for it you mess up sending the address. Sorry. 

# Judging 

July 6th 2023 I'll start judging, and I will award prizes to the following different categories:
1. Most reach 
2. How funny it is 
3. How many web2 developers take the course based off your content
5. How good the SEO is
6. How creative it is

An entry can only win on one of the categories. 

I will give out at least 2 awards to each of the following mediums:
- TikTok / YouTube shorts
- Twitter Threads
- LinkedIn posts
- YouTube videos
- Blogs
- Meme on Reddit
- Something else

So yes, if you have a banger tweet, that's eligible. 

Sadly, I don't have time to coordinate a DAO around this, so judging will be 100% my discretion. If you don't like my judging, too bad 😜

**Comment by PatrickAlphaC** [comment]
Already cooking @alymurtazamemon! Love it!

**Comment by m0ham3dx** [comment]
![](https://media.tenor.com/rcT1ZHSqlZoAAAAC/mario-represent.gif)

---

$$ 
\huge \color{yellow}{Added  \ to \ official \ foundry \ manual}
$$

---
1. Created this [PR](https://github.com/foundry-rs/book/pull/914) , which puts your tutorial on the official manual - [HERE](https://book.getfoundry.sh/tutorials/learn-foundry) which I also explained in this [REPLY](https://twitter.com/m0ham3dxx/status/1666848696263225358?s=20)

**Comment by Vinyl-Davyl** [comment]
Doing some critical promotion and bring more people to @PatrickAlphaC and Web3
[Blog Post: Hashnode](https://vinyldavyl.hashnode.dev/inside-the-ultimate-30hours-blockchain-development-course-from-freecodecamp-patrick-collins-reasons-why-you-should-take-this-course)
[Twitter](https://twitter.com/Vinylchi/status/1667490058486665216?s=20)
[LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:7073267800877711360?utm_source=share&utm_medium=member_desktop)

**Comment by mortezashojaei** [comment]
Hey there!
My Linkedin post:
https://www.linkedin.com/posts/mortezashojaei_blockchain-solidity-blockchaindeveloper-activity-7074053708854005761-0Mk2

**Comment by musprodev** [comment]
I'll be working on this on Twitter as soon as possible

**Comment by Shiv2116** [comment]
twitter thread : - https://twitter.com/ShivDixit21/status/1668483735191445505?s=20
Address - 0xD9c8575bD39B7b438d9d799058cB6458e329BEfE

**Comment by Dynomin** [comment]
LinkedIn: https://www.linkedin.com/posts/uxvaibhav_mustwatch-blockchain-developer-activity-7074814681760100352-yIes?utm_source=share&utm_medium=member_desktop

Arbitrum Address: bc1qr85hg0gknln64sn6888la63u09mje68stfde04

**Comment by Prezzy06** [comment]
Hey there!
Tried to make a funny twitter thread with real life example and meme :) 
Twitter : https://twitter.com/Rishikesh_Sahu_/status/1669660110333919236

**Comment by Kali-Decoder** [comment]
Hey , Delay as Ethereum Hahaha 
[Dev.to](https://dev.to/kalidecoder/foundry-test-erc721-sol-postmortem-22kd)
[Linkedin](https://www.linkedin.com/feed/update/urn:li:activity:7076285407671267328/)
[Twitter](https://twitter.com/itsNikku876/status/1670520649142632449)
Wallet Address : 0xcfa038455b54714821f291814071161c9870B891

**Comment by FidelChe** [comment]
iOopp! Boom! Let's Go!
[LinkedIn Post 1](https://www.linkedin.com/posts/edwin-liavaa_foundry-activity-7076151368452866048-hBFP)
[LinkedIn Post 2](https://www.linkedin.com/posts/edwin-liavaa_learn-solidity-blockchain-development-activity-7072225466257985536-XR6y)
[Twitter Post 1](https://twitter.com/EdwinLiavaa/status/1670385743074820096)
[Twitter Post 2](https://twitter.com/EdwinLiavaa/status/1666459840519053312)

**Comment by musprodev** [comment]
After using all the time in the world to create these masterpieces.

[Twitter 🐥](https://twitter.com/muspro__dev/status/1670593399844470784?s=46&t=U-ZLS9R9pPdGHgEWbuvHtg)

[Linkedin](https://www.linkedin.com/posts/musprodev_learn-solidity-blockchain-development-activity-7076379054261641216-8d9V?utm_source=share&utm_medium=member_ios)

Arbitrum: 0x96E248D3C0C0bE6A4b84956F2F7681260716d89d

**Comment by PatrickAlphaC** [comment]
They are!

**Comment by k7seven** [comment]
Hey @PatrickAlphaC!

Does this tweet works?

https://twitter.com/ksevenseven_eth/status/1671112494591401984

My Arbitrum Address: 0x2b3314508b43a3edb60c711465ceda673557b53a

**Comment by kumar-kalyan** [comment]
**Wallet Address** : 0x29A57B05542A06B6Dbc5A188a943c0E9b9d81405

### Twitter threads 
https://twitter.com/0x270A/status/1671060436777574401
https://twitter.com/0x270A/status/1671060419752886277

### LinkedIn Posts:
https://www.linkedin.com/posts/kumar009_github-cyfrinfoundry-full-course-f23-activity-7076479989482733569-eFVL?utm_source=share&utm_medium=member_desktop
https://www.linkedin.com/feed/update/urn:li:activity:7075390655342014464?utm_source=share&utm_medium=member_desktop
https://www.linkedin.com/posts/kumar009_github-cyfrinfoundry-full-course-f23-activity-7075390605484310528-a9Y2?utm_source=share&utm_medium=member_desktop
https://www.linkedin.com/posts/kumar009_learn-solidity-blockchain-development-activity-7075011164597882880-htvm?utm_source=share&utm_medium=member_desktop

**Comment by Marcolopeez** [comment]
Wallet Address: 0x6114728E46731890ce99F2CB3e5F38f7C79143E8

·Twitter thread: https://twitter.com/Marcologonz/status/1672205067854675968?s=20
·LinkedIn Post: https://www.linkedin.com/posts/marcologonz_learn-solidity-blockchain-development-activity-7077965669664702465-VIKs?utm_source=share&utm_medium=member_desktop

Thank you very much Patrick, I really enjoy the course!

**Comment by ShayanShamsi** [comment]
Hey @PatrickAlphaC!
I am planning to host sessions at my university where students and alumni will get together, complete the course, and just have a fun time together. And of course, I and the relevant clubs/societies at my university will also be making posts to promote the event. We will probably stream our sessions online as well.
Is this campaign eligible for participation?

**Comment by PatrickAlphaC** [comment]
@ShayanShamsi sure is!

**Comment by veridelisi** [comment]
Hi patrick man

https://twitter.com/VeriDelisi/status/1675930987169980421

Wallet Address:  0x1bc6dbb7Ea134dA647eaDb037D99E5F691Ff4286

Turkish followers

**Comment by IAm0xTime** [comment]
Hey ser, Are Twitter/Blog threads like these eligible for the prize pool?

I've combined your and Taylor's courses to make a full time blockchain security learner course. Because I think the best way to promote this is to put Secureum's course in and combine it into a learning schedule. This will be more beneficial for beginners to understand the route they want to take after taking this course (blockchain development OR blockchain security).  Looking forward to being helpful to more beginners, please check it out. ![image](https://github.com/Cyfrin/foundry-full-course-f23/assets/33568293/db987ab3-d8c8-4db8-903a-43a25032393c)

Finally, thank you very sincerely for the course, it was like a godsend for us beginners. I'm also recommending this course to my friends!

**Twitter:** 
1. https://twitter.com/IAm0xTime/status/1675743329068400640 
2. https://twitter.com/IAm0xTime/status/1675746579062616065

**Blog:**
1. https://0xtime.xlog.app/The-best-beginner-coursesmd

**My Arbitrum Address:**  0x44E209E2C299048FCB60AC65dcAA9F7D7980a1d2

**Comment by RoboCrypter** [comment]
[Twitter Thread 1](https://twitter.com/RoboCrypter/status/1670568616214040577)

[Twitter Thread 2](https://twitter.com/RoboCrypter/status/1676666687427592192)

[Twitter Thread 3](https://twitter.com/RoboCrypter/status/1669290329990893568)

[Meme on Twitter](https://twitter.com/RoboCrypter/status/1674024848828547072)

[Dev.to Blog](https://dev.to/robocrypter/journey-into-blockchain-development-1cj8)

[LinkedIn Post](https://www.linkedin.com/feed/update/urn:li:activity:7078989970710884352/)

**Comment by Genesis3800** [comment]
Hey @PatrickAlphaC ,
submitting this blog as my only official submission.
I hope I am in time for the bounty.]

My wallet address: 0xfbD8eb2aAd1cbFca38E33917B0CD70981172bf1B

[The most detailed article on Chainlink VRF to exist](https://blog.developerdao.com/the-developers-guide-to-chainlink-vrf-foundry-edition)

**Comment by socopower** [comment]
Hi guys, here is my contribution to this little campaign, I hope you like it.

[My Twitter](https://twitter.com/dserrano01/)
[My Reddit](https://www.reddit.com/u/dserrano10)
[My Medium](https://medium.com/@kristhiann97)


**1) Reddit Posts:** Sadly they were eliminated by the Mods, I suspect it was because I put my address in the post, I will attach screenshots of the posts.

- [Post #1](https://www.reddit.com/r/ethereum/comments/14mdiyg/finally_patrick_collinss_full_solidity_course_is/)
- [Post #2](https://www.reddit.com/r/Avax/comments/14mehm2/finally_patrick_collinss_full_solidity_course_is/)
- [SS #1](https://imgur.com/a/0Vkwqqp)
- [SS #2](https://imgur.com/a/OycpXgI)

**2) Twitter Memes/Threads:**

- [Thread](https://twitter.com/dserrano01/status/1676676621401575448)
- [Thread of Memes](https://twitter.com/dserrano01/status/1674598055155302401)

**3) Medium Article:** 

- [The Best Way To Start Learning Web3 Development: Patrick Collins's Full Solidity Course! Walkthrough 1/3](https://medium.com/@kristhiann97)


**Thanks again to Patrick for preparing and teaching us excellent material such as this 3rd Edition of his Solidity Course!.**

My next goal after finishing this course is to take the course on **How to Make a Stablecoin with Foundry.**

**Comment by PatrickAlphaC** [comment]
Thank you all for these awesome submissions!!

I will start the judging today :)

**Comment by Shiv2116** [comment]
@PatrickAlphaC I was unable to leave a comment of my daily twitter thread over here ,but i have commented the first time, will it count?

**Comment by michealfortunatus** [comment]
oops my materials are ready

**Comment by PatrickAlphaC** [comment]
@Shiv2116 yes!

**Comment by PatrickAlphaC** [comment]
0.134067

Top 20 Winners! Transactions have been sent. 
- @alymurtazamemon 
- @m0ham3dx (need your wallet address)
- @Vinyl-Davyl 
- @mortezashojaei 
- @Shiv2116 
- @edsondsouza 
- @Dynomin (need arbitrum address)
- @Prezzy06 
- @Kali-Decoder 
- @FidelChe 
- @musprodev 
- @kumar-kalyan 
- @Marcolopeez 
- @ShayanShamsi (need wallet address)
- @veridelisi 
- @IAm0xTime 
- @RoboCrypter 
- @Genesis3800 
- @edakturk14 (need wallet address)
- @socopower 

And the grand prize goes to...
- @akhilmanga 

For the AMAZING memes!!

Thanks, everyone for participating! Let's continue to make this the most badass course out there!

**Comment by musprodev** [comment]
Thanks very much Sir Patrick 😭. I've always been your disciple. This is a very big opportunity and we continue building ☺️

**Comment by FidelChe** [comment]
> Top 20 Winners! Transactions have been sent.
> 
> * @alymurtazamemon
> * @m0ham3dx (need your wallet address)
> * @Vinyl-Davyl
> * @mortezashojaei
> * @Shiv2116
> * @edsondsouza
> * @Dynomin (need arbitrum address)
> * @Prezzy06
> * @Kali-Decoder
> * @FidelChe
> * @musprodev
> * @kumar-kalyan
> * @Marcolopeez
> * @ShayanShamsi (need wallet address)
> * @veridelisi
> * @IAm0xTime
> * @RoboCrypter
> * @Genesis3800
> * @edakturk14 (need wallet address)
> * @socopower
> 
> And the grand prize goes to...
> 
> * @akhilmanga
> 
> For the AMAZING memes!!
> 
> Thanks, everyone for participating! Let's continue to make this the most badass course out there!

Woohoo! Tons of thanks @PatrickAlphaC Bravo Everyone! Let's continue to make this the most badass course out there! Boom! Let's Go!

**Comment by musprodev** [comment]
> Let's go bro

**Comment by ShayanShamsi** [comment]
Thankyou @PatrickAlphaC! And yes lets continue to spread this course like wildfire 🔥 This is a goldmine!

And here is my wallet address: 0xE4A998B63a4842AF250Da90c032D90A56D9f44dB

Thanks again :)

**Comment by socopower** [comment]
> Top 20 Winners! Transactions have been sent.
> 
> * @alymurtazamemon
> * @m0ham3dx (need your wallet address)
> * @Vinyl-Davyl
> * @mortezashojaei
> * @Shiv2116
> * @edsondsouza
> * @Dynomin (need arbitrum address)
> * @Prezzy06
> * @Kali-Decoder
> * @FidelChe
> * @musprodev
> * @kumar-kalyan
> * @Marcolopeez
> * @ShayanShamsi (need wallet address)
> * @veridelisi
> * @IAm0xTime
> * @RoboCrypter
> * @Genesis3800
> * @edakturk14 (need wallet address)
> * @socopower
> 
> And the grand prize goes to...
> 
> * @akhilmanga
> 
> For the AMAZING memes!!
> 
> Thanks, everyone for participating! Let's continue to make this the most badass course out there!

Wow, Thank you so much for the reward, I really appreciate it so much... ✨

I already want to finish the course to do part 2 & 3 of my Walkthrough.

**Comment by Vinyl-Davyl** [comment]
> Top 20 Winners! Transactions have been sent.
> 
> * @alymurtazamemon
> * @m0ham3dx (need your wallet address)
> * @Vinyl-Davyl
> * @mortezashojaei
> * @Shiv2116
> * @edsondsouza
> * @Dynomin (need arbitrum address)
> * @Prezzy06
> * @Kali-Decoder
> * @FidelChe
> * @musprodev
> * @kumar-kalyan
> * @Marcolopeez
> * @ShayanShamsi (need wallet address)
> * @veridelisi
> * @IAm0xTime
> * @RoboCrypter
> * @Genesis3800
> * @edakturk14 (need wallet address)
> * @socopower
> 
> And the grand prize goes to...
> 
> * @akhilmanga
> 
> For the AMAZING memes!!
> 
> Thanks, everyone for participating! Let's continue to make this the most badass course out there!

Really glad to be among the top 20. I enjoyed every part of it on doing the lords work promoting web3 and this awesome course in genenral. Thank you so much @PatrickAlphaC It's really been a great honour✨🎉 Cheers to everyone too.🎉

**Comment by edsondsouza** [comment]
Woohoo!! I WON!!!
No, but honestly thank you so much for creating this amazing course 

- ❤️

**Comment by m0ham3dx** [comment]
> Top 20 Winners! Transactions have been sent.
> 
> * @alymurtazamemon
> * @m0ham3dx (need your wallet address)
> * @Vinyl-Davyl
> * @mortezashojaei
> * @Shiv2116
> * @edsondsouza
> * @Dynomin (need arbitrum address)
> * @Prezzy06
> * @Kali-Decoder
> * @FidelChe
> * @musprodev
> * @kumar-kalyan
> * @Marcolopeez
> * @ShayanShamsi (need wallet address)
> * @veridelisi
> * @IAm0xTime
> * @RoboCrypter
> * @Genesis3800
> * @edakturk14 (need wallet address)
> * @socopower
> 
> And the grand prize goes to...
> 
> * @akhilmanga
> 
> For the AMAZING memes!!
> 
> Thanks, everyone for participating! Let's continue to make this the most badass course out there!

![](https://media.tenor.com/EdbKVcCdzlsAAAAC/army-fist-bump.gif)

Arbitrum Eth Address
---
[0xBABC11dA04665817bA832395DdeC2166772cc1d2](https://arbiscan.io/address/0xBABC11dA04665817bA832395DdeC2166772cc1d2)

---

Quite unexpected ! , atm im in some rabbit holes of a few langs , once i get out of it will put a little bit more focus on Smart Contract Dev , and ofcourse parse through this amazing course !

**Comment by PatrickAlphaC** [comment]
> 0xE4A998B63a4842AF250Da90c032D90A56D9f44dB

Sent! Thank you!

**Comment by PatrickAlphaC** [comment]
> Thankyou @PatrickAlphaC! And yes lets continue to spread this course like wildfire 🔥 This is a goldmine!
> 
> And here is my wallet address: 0xE4A998B63a4842AF250Da90c032D90A56D9f44dB
> 
> Thanks again :)

sent, thank you!

**Comment by PatrickAlphaC** [comment]
> > Top 20 Winners! Transactions have been sent.
> > 
> > * @alymurtazamemon
> > * @m0ham3dx (need your wallet address)
> > * @Vinyl-Davyl
> > * @mortezashojaei
> > * @Shiv2116
> > * @edsondsouza
> > * @Dynomin (need arbitrum address)
> > * @Prezzy06
> > * @Kali-Decoder
> > * @FidelChe
> > * @musprodev
> > * @kumar-kalyan
> > * @Marcolopeez
> > * @ShayanShamsi (need wallet address)
> > * @veridelisi
> > * @IAm0xTime
> > * @RoboCrypter
> > * @Genesis3800
> > * @edakturk14 (need wallet address)
> > * @socopower
> > 
> > And the grand prize goes to...
> > 
> > * @akhilmanga
> > 
> > For the AMAZING memes!!
> > Thanks, everyone for participating! Let's continue to make this the most badass course out there!
> 
> ![](https://camo.githubusercontent.com/8e1c54c326f922da1abf1653afba4bd8b65a11e2ce32ab0c114cb0930580a9e1/68747470733a2f2f6d656469612e74656e6f722e636f6d2f4564624b566343647a6c7341414141432f61726d792d666973742d62756d702e676966) [ ![68747470733a2f2f6d656469612e74656e6f722e636f6d2f4564624b566343647a6c7341414141432f61726d792d666973742d62756d702e676966](https://camo.githubusercontent.com/8e1c54c326f922da1abf1653afba4bd8b65a11e2ce32ab0c114cb0930580a9e1/68747470733a2f2f6d656469612e74656e6f722e636f6d2f4564624b566343647a6c7341414141432f61726d792d666973742d62756d702e676966) ](https://camo.githubusercontent.com/8e1c54c326f922da1abf1653afba4bd8b65a11e2ce32ab0c114cb0930580a9e1/68747470733a2f2f6d656469612e74656e6f722e636f6d2f4564624b566343647a6c7341414141432f61726d792d666973742d62756d702e676966) [ ](https://camo.githubusercontent.com/8e1c54c326f922da1abf1653afba4bd8b65a11e2ce32ab0c114cb0930580a9e1/68747470733a2f2f6d656469612e74656e6f722e636f6d2f4564624b566343647a6c7341414141432f61726d792d666973742d62756d702e676966)
> 
> ## Arbitrum Eth Address
> [0xBABC11dA04665817bA832395DdeC2166772cc1d2](https://arbiscan.io/address/0xBABC11dA04665817bA832395DdeC2166772cc1d2)
> 
> Quite unexpected ! , atm im in some rabbit holes of a few langs , once i get out of it will put a little bit more focus on Smart Contract Dev , and ofcourse parse through this amazing course !
> 
> Oh and congrats to the all the participants and the grand prize winner - memes are LOL !

Sent! Thank you!

**Comment by PatrickAlphaC** [comment]
Just need:

```
@Dynomin (need arbitrum address)
@edakturk14 (need wallet address)
```

**Comment by akhilmanga** [comment]
SIr. Thank you so much. How much did you enjoy the content sir (?/100)

**Comment by PatrickAlphaC** [comment]
10/10 @akhilmanga lmao great work

**Comment by IAm0xTime** [comment]
> Top 20 Winners! Transactions have been sent.
> 
> * @alymurtazamemon
> * @m0ham3dx (need your wallet address)
> * @Vinyl-Davyl
> * @mortezashojaei
> * @Shiv2116
> * @edsondsouza
> * @Dynomin (need arbitrum address)
> * @Prezzy06
> * @Kali-Decoder
> * @FidelChe
> * @musprodev
> * @kumar-kalyan
> * @Marcolopeez
> * @ShayanShamsi (need wallet address)
> * @veridelisi
> * @IAm0xTime
> * @RoboCrypter
> * @Genesis3800
> * @edakturk14 (need wallet address)
> * @socopower
> 
> And the grand prize goes to...
> 
> * @akhilmanga
> 
> For the AMAZING memes!!
> 
> Thanks, everyone for participating! Let's continue to make this the most badass course out there!

Woohoo! Thank you so much @PatrickAlphaC! Let's keep spreading the word about this excellent course! 🔥

**Comment by 0xinit** [comment]
Kill me for forgetting to actually submit my tweets and my community's work here :sob: :skull: 

But congratulations to all the winners!! Good work, ser @PatrickAlphaC

**Comment by Shiv2116** [comment]
Thank you @PatrickAlphaC ,still cant believe and process 
Thank you for the most loved course on the planet 
🥳🥳🥳
LFG🚀

**Comment by mortezashojaei** [comment]
Thanks, man heart!

**Comment by Kali-Decoder** [comment]
Thanks Man ❤️ !

**Comment by veridelisi** [comment]
> Top 20 Winners! Transactions have been sent.
> 
> * @alymurtazamemon
> * @m0ham3dx (need your wallet address)
> * @Vinyl-Davyl
> * @mortezashojaei
> * @Shiv2116
> * @edsondsouza
> * @Dynomin (need arbitrum address)
> * @Prezzy06
> * @Kali-Decoder
> * @FidelChe
> * @musprodev
> * @kumar-kalyan
> * @Marcolopeez
> * @ShayanShamsi (need wallet address)
> * @veridelisi
> * @IAm0xTime
> * @RoboCrypter
> * @Genesis3800
> * @edakturk14 (need wallet address)
> * @socopower
> 
> And the grand prize goes to...
> 
> * @akhilmanga
> 
> For the AMAZING memes!!
> 
> Thanks, everyone for participating! Let's continue to make this the most badass course out there!

Thank you 3d no sleeping hd full blue tick great developer Patrick

**Comment by RoboCrypter** [comment]
@PatrickAlphaC Thank you for your invaluable knowledge and the incredible opportunities you've provided us. Your contributions are truly amazing and much appreciated!

I will forever be grateful for the profound impact you've had on my journey. ThankYou!

**Comment by edakturk14** [comment]
> Just need:
> 
> ```
> @Dynomin (need arbitrum address)
> @edakturk14 (need wallet address)
> ```

Thanks a million!! Literally got to watch one of the best courses + win a price. Beyond grateful  Congrats to all the winners as well!! 

Forgot to add my address, here it is if I'm not too late :) 0xc4Ac4174AA9A93d9eef02621cE8205C75D003dE5

**Comment by Marcolopeez** [comment]
> Top 20 Winners! Transactions have been sent.
> 
> * @alymurtazamemon
> * @m0ham3dx (need your wallet address)
> * @Vinyl-Davyl
> * @mortezashojaei
> * @Shiv2116
> * @edsondsouza
> * @Dynomin (need arbitrum address)
> * @Prezzy06
> * @Kali-Decoder
> * @FidelChe
> * @musprodev
> * @kumar-kalyan
> * @Marcolopeez
> * @ShayanShamsi (need wallet address)
> * @veridelisi
> * @IAm0xTime
> * @RoboCrypter
> * @Genesis3800
> * @edakturk14 (need wallet address)
> * @socopower
> 
> And the grand prize goes to...
> 
> * @akhilmanga
> 
> For the AMAZING memes!!
> 
> Thanks, everyone for participating! Let's continue to make this the most badass course out there!

Thank you so much @PatrickAlphaC, amazing course + winning a price... Wow. Very motivating, congratulations also to all those who enjoy the course content!! Lets keep moving
