### ISSUE TITLE
Error with running "forge script"

### ISSUE THREAD

**Issue by AnthonyHarvey8867** [Cyfrin/foundry-full-course-f23#1050]
Hey guys,
I'm having difficulties with the last part of video 1; deploying "SimpleStorage.sol" in foundry; where there is a script to deploy the smart contract.
here is the script from the first video of the course:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

// import {Script} from "../lib/forge-std/src/Script.sol";
import {Script} from "forge-std/Script.sol";
import {SimpleStorage} from "../src/SimpleStorage.sol";

contract DeploySimpleStorage is Script {
    function run() external returns (SimpleStorage) {
        vm.startBroadcast();
        SimpleStorage simpleStorage = new SimpleStorage();
        vm.stopBroadcast();
        return simpleStorage;
    }
}
```

then when I run "forge script scr/SimpleStorage.sol" in the command line. I get the following error:
```
[⠊] Compiling...
[⠃] Compiling 22 files with 0.8.21
[⠰] Solc 0.8.21 finished in 4.80s
Compiler run successful!
Error: 
Function `run()` is not implemented in your script.
```

I have tried the command with other test files but the issue still persists!

anyone has any ideas as to why it keeps referring to "run() " function while it has been defined within the script!

**Comment by gKrithick** [comment]
isn't the command for running the script file should be forge script src/SimpleStorage.s.sol ??? or if you've name your folder and file to be scr and SimpleStorage respectively you shouldn't face any problem since I don't see any problem with the code!

**Comment by lpetroulakis** [comment]
as mentioned above, the command you should probably use is the following
```
forge script script/DeploySimpleStorage.s.sol
```

**Comment by GhislainTselone** [comment]
Hello buddy ! 
Here is the right script to deploy the contract on the local chain :  

```
forge script script/DeploySimpleStorage.s.sol --rpc-url $RPC_URL    --broadcast             --private-key $PRIVATE_KEY 
```

Hope it helps :)

**Comment by musaCODEzz** [comment]
how do i get the fork url that I am constantly getting requested to have

**Comment by KAravind2005** [comment]
The file name has to be SimpleStorage.s.sol
