### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/foundry-full-course-f23#11]
### Describe the enhancement

Each section of the video is broken up by a screen that looks like this:
<img width="1845" alt="Screenshot 2023-06-06 at 1 28 56 PM" src="https://github.com/Cyfrin/foundry-full-course-f23/assets/54278053/7d6a609b-26bc-49af-a788-fca5ff773b9e">

It would be great if we could add timestamps in this repo for each one of these.

**Comment by Redidacove** [comment]
where I have to update  the timestamps plz mention try to do that

**Comment by PatrickAlphaC** [comment]
Each section like this in the README
<img width="302" alt="Screenshot 2023-06-08 at 10 28 26 AM" src="https://github.com/Cyfrin/foundry-full-course-f23/assets/54278053/724145eb-c088-43bb-8f7a-356f023ba3bd">

Should come with a timestamp

**Comment by f3d0ss** [comment]
Currently, we have timestamps for lessons ranging from 0 to 12. Additionally, there is [PR #45](https://github.com/Cyfrin/foundry-full-course-f23/pull/45) that extends the timestamps up to lesson 14. Moreover, I have submitted [PR #299](https://github.com/Cyfrin/foundry-full-course-f23/pull/299) for lesson 15. If both of these PRs are accepted, the timestamps will be fully completed.

**Comment by PatrickAlphaC** [comment]
Closing, most of them are in here!
