### ISSUE TITLE
I am trying to compile my code and i am getting this error message. Please, I need help with this.

### ISSUE THREAD

**Issue by Goodybag1** [Cyfrin/foundry-full-course-f23#1211]
I am trying to compile my code and i am getting this error message. Please, I need help with this.

ParserError: Expected primary expression.
  --> FundMe.sol:25:2:
   |![Screenshot (11)](https://github.com/Cyfrin/foundry-full-course-f23/assets/137379948/5ea280dc-f2a8-4660-b601-56ca56ca0867)
![Screenshot (10)](https://github.com/Cyfrin/foundry-full-course-f23/assets/137379948/994162d6-42bd-419d-a347-a4868b3dbe1a)

_Originally posted by @Goodybag1 in https://github.com/Cyfrin/foundry-full-course-f23/discussions/1210_

**Comment by KAravind2005** [comment]
Remove that comma bro. Before int256

**Comment by Goodybag1** [comment]
> Remove that comma bro. Before int256

Thanks bro, i already did that but It still draws a red squiggly line under "price".  I coded along with Patrick, i don't know why I'm getting the error.

**Comment by KAravind2005** [comment]
Can you attach the pic

**Comment by Goodybag1** [comment]
> Can you attach the pic
Will send that later, I'm in transit and not with my PC. Thank you bro.

**Comment by KAravind2005** [comment]
Ok. No problem. Give ur ig we will connect there

**Comment by Goodybag1** [comment]
I'm not on Ig.
Only Tg, discord, WhatsApp. Which do you prefer?

**Comment by KAravind2005** [comment]
Discord and tg. Ur choice

**Comment by Goodybag1** [comment]
> Discord and tg. Ur choice

Tg: @Goodybaggy

**Comment by KAravind2005** [comment]
See I text you in tg

**Comment by Mohsen2083** [comment]
Hello @Goodybag1 !

you need to put *1e10 inside () with price, meaning your code should look like the screenshot below:
![Screenshot 2023-12-27 205909](https://github.com/Cyfrin/foundry-full-course-f23/assets/131712492/60e12857-b607-4fab-b779-6799a16d9f8e)


Hope this helps😸😸
