### ISSUE TITLE
source .env

### ISSUE THREAD

**Issue by Vodvalex** [Cyfrin/foundry-full-course-f23#1235]
I am trying to execute a command $ source .env. Also I am in the folder : foundry-simple-storage-f23.Unfortunately it shows: "bash: .env: No such file or directory"
I have checked twice that the .env in the in the Gitignore folder under  #Dotenv file
I have saved the .env in the test folder.
May be someone else also have got the same  problem? PLease help. Thank you.

**Comment by Mohsen2083** [comment]
Hello @Vodvalex,1: make sure you are putting no space next to "=" meaning:
PUBLIC_KEY=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266,
not PUBLIC_KEY = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

and btw your .env file should not be inside your test folder and your folder should look like something like this:

![Screenshot 2023-12-24 151211](https://github.com/Cyfrin/foundry-full-course-f23/assets/131712492/12adce1a-a5d5-4d2b-801c-47a0bb62dbb7)

after making sure you are creating .env file in the right position try typing source .env inside your bash terminal.
I hope this helps,

**Comment by Vodvalex** [comment]
Dear @Mohsen2083 .Thank you very much for your help.I have followed  your clear explaination and this time it did work. Your help is much appriciated.

**Comment by Mohsen2083** [comment]
> Dear @Mohsen2083 .Thank you very much for your help.I have followed your clear explaination and this time it did work. Your help is much appriciated.

Glad that I could be of assistance fren😸😸😸

**Comment by darom1998** [comment]
Thanks [Mohsen2083](https://github.com/Mohsen2083) it's working properly

**Comment by cromewar** [comment]
seems to be solved.
