### ISSUE TITLE
Broken link to get the ABI interface for Lesson 4 | Fund Me

### ISSUE THREAD

**Issue by nseguias** [Cyfrin/foundry-full-course-f23#1261]
### Describe the enhancement

When trying to follow along the video there's no AggregatorV3Interface.sol file in the chainlink repo. You can find it here (https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.7/interfaces/AggregatorV3Interface.sol) instead (not in v08 though) but I'm not sure if they're the same.

Interfaces
[⌨️ (4:37:08) | Interfaces](https://youtu.be/umepbfKp5rI?t=16628)

For reference - [ChainLink Interface's Repo](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol)

**Comment by cromewar** [comment]
Please make a pr with this enhancement to the docs, and I will merge it :D

**Comment by 13zebras** [comment]
Someone submitted this PR back in January for this issue. Please merge so that others won't have to hunt for this interface in the Chainlink repo. Thanks!
https://github.com/Cyfrin/foundry-full-course-f23/pull/1361

**Comment by PatrickAlphaC** [comment]
Done!
