### ISSUE TITLE
Lesson 6 :  Ganache URL not connecting  while deploying  SimpleStorage contract

### ISSUE THREAD

**Issue by Meherabhossen** [Cyfrin/foundry-full-course-f23#1294]
### Discussed in https://github.com/Cyfrin/foundry-full-course-f23/discussions/1282

<div type='discussions-op-text'>

<sup>Originally posted by **Meherabhossen** January  4, 2024</sup>
im getting error on this

```
[⠊] Compiling...
No files changed, compilation skipped
Error: 
error sending request for url (http://127.0.0.1:7545/): error trying to connect: tcp connect error: Connection refused (os error 111)

Context:
- Error #0: error trying to connect: tcp connect error: Connection refused (os error 111)
- Error #1: tcp connect error: Connection refused (os error 111)
- Error #2: Connection refused (os error 111)

```

this is my command 
```
forge create SimpleStorage --rpc-url http://127.0.0.1:7545 --interactive
```</div>

**Comment by parwejkhan1816** [comment]
try to change the port number in ganache . Sometime firewall blocking access to some port in PC . 
Also check anvil is not running on same port  
https://github.com/Cyfrin/foundry-full-course-f23/discussions/318
https://github.com/Cyfrin/foundry-full-course-f23/discussions/873
Take a look on above url , hope this help

**Comment by darom1998** [comment]
I run this command
forge create SimpleStorage --rpc-url http://127.0.0.1:7550 --interactive
But this errors had appeared , solution please §§
****
[⠃] Compiling...No files changed, compilation skipped
[⠊] Compiling...
Error: 
error sending request for url (http://127.0.0.1:7550/): error trying to connect: tcp connect error: Connection refused (os error 111)

Context:
- Error #0: error trying to connect: tcp connect error: Connection refused (os error 111)
- Error #1: tcp connect error: Connection refused (os error 111)
- Error #2: Connection refused (os error 111)

**Comment by Winter9998** [comment]
>     * Error #0: error trying to connect: tcp connect error: Connection refused (os error 111)

Hi,

This error generally pops up when there is a TCP Connection problem meaning that your CLI cannot connect. What you should try to do is this :

1.  Close the actual Terminal you're using ( Bash, Zsh, WSL ) and make another one
2.  in the temrinal type : `foundryup`
3.  Before trying on Gananche try to use the `--rpc-url` with anvil first by opening a second terminal and typing `anvil` use the rpc url of it generally it's : http://127.0.0.1:8545
4. Restart VsCode
5.  Be sure to verify you have a solid connection and that you're not far away from a wireless device for example
6. Restart the Computer 

Try this

**Comment by cryptjohel** [comment]
To solve this issue u have to open a new terminal with same directory to initialize ```Anvil``` so to show it is running already


And your code line is not complete due to using interactive is to the fact there should be a private key that you should either use .env or using the latest keystore method 


Or if you don't want to do that u can just compile it by using ```forge create SimpleStorage``` it will automatically create using anvil default way but when u need to specify with private key follow the steps I gave you

**Comment by Chujimafa** [comment]
if u use the wsl in vs code, you have to make sure ganache also in wsl, so you need to create a new wroking space in ganache und change it to wsl

**Comment by cryptjohel** [comment]
Thanks for the tip!

**Comment by PatrickAlphaC** [comment]
Going to close this for now, those who end up here, please see the discussion!
