### ISSUE TITLE
Twitter bot that congratulates people when they mint an arbitrum NFT

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/foundry-full-course-f23#13]
### Describe the enhancement

Our NFTs allow people to add their twitter handle, it would be awesome if we had a bot tweet to someone's handle whenever they minted an NFT! 

Here is the contract:
https://arbiscan.io/address/0x39338138414Df90EC67dC2EE046ab78BcD4F56D9#code

Additionally, having a website that shows a real-time list of people minting would be awesome. 

I'm down to pay someone to work on this as well!

**Comment by shankars99** [comment]
I could try out the bot as soon as I get my Chainlink Spring Hackathon submission up (so in like a few days) if that works

**Comment by PatrickAlphaC** [comment]
@shankars99 

That works lovely!

**Comment by lostintime101** [comment]
Would also be interested in putting this together. Cool little project

**Comment by Nkemjieme** [comment]
Here's an outline of the steps you can follow to implement this enhancement:

Set up a Twitter Developer Account: To access the Twitter API, you'll need to create a developer account and set up a Twitter App. This will provide you with the necessary API keys and access tokens to authenticate your requests.

Install Twitter API Client Library: Use a Twitter API client library in your preferred programming language (such as Tweepy for Python) to simplify the interaction with the Twitter API. You'll need to install the library and configure it with your API keys and access tokens.

Write the Mint Event Listener: In your smart contract, add an event listener for the "mint" event. Whenever a new NFT is minted, emit this event with the necessary information, such as the owner's Twitter handle.

Connect the Backend and Smart Contract: In your backend application (Flask), set up a listener for the "mint" event using the appropriate Ethereum library (such as Web3.py). When the event is triggered, retrieve the necessary information and call the Twitter API to send a tweet to the specified Twitter handle.

Real-time List of People Minting: To display a real-time list of people minting NFTs, you can use WebSockets or a similar technology to establish a bi-directional communication channel between the backend and the frontend. Whenever a new "mint" event is received in the backend, send the updated list of minted NFTs to the frontend through the WebSocket connection.

Update the Frontend: In your frontend application (React), subscribe to the WebSocket connection to receive the real-time updates of minted NFTs. Update the list displayed on the website whenever a new NFT is minted.

**Comment by egeaybars123** [comment]
Working on it.

**Comment by d1-dblaze** [comment]
Hey, I'm interested. I will like to work with someone on this. Kindly check my bio and dm me on twitter.

**Comment by 0xAnon0602** [comment]
Working on this

**Comment by RomitoVincenzo** [comment]
Hi guys, here to help!

**Comment by Ankur-Thakur-NEU** [comment]
Hey Patrick. I'd be really interested in working on this.

**Comment by michealfortunatus** [comment]
Let's get it started

I am taking up this

**Comment by 0xn4de** [comment]
Let me know what you think.
https://github.com/0xn4de/foundry-course-bot

**Comment by kanvgupta** [comment]
Deployed a local version here https://twitter.com/matic_eth
(Tested with Uniswap's Transfer events)

Let me know if you want me to finish this

**Comment by 0xAnon0602** [comment]
@PatrickAlphaC 
Was able to get this working 
https://github.com/0xAnon0602/Foundery-Course-Twitter-Bot

**Comment by usman-2000** [comment]
it's time to dig hands on this project. I am going to start working on this project.

**Comment by Markeljan** [comment]
Had some fun with this. (and some not fun dealing with Twitter API)

[Frontend Trackoor](https://foundry-mints.vercel.app/)
![image](https://github.com/Cyfrin/foundry-full-course-f23/assets/12901349/84ee315a-98a7-45ec-b35f-ca16bf7b5154)

[Repositoory](https://github.com/Markeljan/foundry-course-mint-bot/settings)

[Twitter Bot](https://twitter.com/foundrymintbot)
![image](https://github.com/Cyfrin/foundry-full-course-f23/assets/12901349/371c66be-09dd-489c-9def-e81da83a1852)

**Comment by turazashvili** [comment]
If by any chance this is what you wanted to see - let me know :) 
https://twitter.com/axrisi/status/1667874938928111617

**Comment by egeaybars123** [comment]
Done! 
Frontend Link: https://arb-nft-frontend.vercel.app/
Twitter Bot: https://twitter.com/FoundryCongrats

**Comment by PatrickAlphaC** [comment]
@kanvgupta 
@0xAnon0602 
@0xn4de 
@Markeljan 
@egeaybars123 

Let's DM. Everyone else please stop working on this!

**Comment by RichardPalladino** [comment]
(I'm running an Arbitrum node, if people feel like getting the bot to query the blockchain for free... not sure what your polling rate / RPC consumption is going to be.)

**Comment by Muhammad-Shahrukh-Azeem** [comment]
> ### Describe the enhancement
> Our NFTs allow people to add their twitter handle, it would be awesome if we had a bot tweet to someone's handle whenever they minted an NFT!
> 
> Here is the contract: https://arbiscan.io/address/0x39338138414Df90EC67dC2EE046ab78BcD4F56D9#code
> 
> Additionally, having a website that shows a real-time list of people minting would be awesome.
> 
> I'm down to pay someone to work on this as well!

I would love to do this.

**Comment by RichardPalladino** [comment]
You guys are RAD!  Super fast turnaround.  I just minted a couple NFTs and wouldn't you know it got instantly posted to Twitter.
