### ISSUE TITLE
VULNERABILITY! redeemCollateral and redeemCollateralForDsc need to have isAllowedToken(tokenCollateralAddress) modifier

### ISSUE THREAD

**Issue by nzlatev7** [Cyfrin/foundry-full-course-f23#1329]
### Lesson

Lesson 12

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://youtu.be/wUjYK5gwNZs?t=8205

### Operating System

Windows

### Describe the bug

# redeemCollateral and redeemCollateralForDsc need to have isAllowedToken(tokenCollateralAddress) modifier

## Summary
Everyone can call redeemCollateral and redeemCollateralForDsc with address that is not allowed. This vulnerability may result in a critical error, specifically: `[FAIL. Reason: panic: arithmetic underflow or overflow (0x11)]`. This error occurs when attempting to subtract an amount from zero in the following code snippet:  `s_collateralDeposited[from][tokenCollateralAddress] -= amountCollateral;`

## Code Snippet
https://github.com/Cyfrin/foundry-defi-stablecoin-f23/blob/7dca86be19d3eea563daa599d3c73840eff16437/src/DSCEngine.sol#L151C8-L151C8

https://github.com/Cyfrin/foundry-defi-stablecoin-f23/blob/7dca86be19d3eea563daa599d3c73840eff16437/src/DSCEngine.sol#L166

## Tool used

Manual Review

## Recommendation
Include isAllowedToken(tokenCollateralAddress) modifier. This will revert if invalid collateral address is passed.

```diff
function redeemCollateralForDsc(address tokenCollateralAddress, uint256 amountCollateral, uint256 amountDscToBurn)
        external
        moreThanZero(amountCollateral)
+      isAllowedToken(tokenCollateralAddress)
    {
        _burnDsc(amountDscToBurn, msg.sender, msg.sender);
        _redeemCollateral(tokenCollateralAddress, amountCollateral, msg.sender, msg.sender);
        revertIfHealthFactorIsBroken(msg.sender);
    }

    function redeemCollateral(address tokenCollateralAddress, uint256 amountCollateral)
        external
        moreThanZero(amountCollateral)
+      isAllowedToken(tokenCollateralAddress)
        nonReentrant
    {
        _redeemCollateral(tokenCollateralAddress, amountCollateral, msg.sender, msg.sender);
        revertIfHealthFactorIsBroken(msg.sender);
    }
```

**Comment by cromewar** [comment]
Can you submit a PR for this @nzlatev7?

**Comment by nzlatev7** [comment]
not yet! To try or?

**Comment by nzlatev7** [comment]
> Can you submit a PR for this @nzlatev7?

Yea, I can submit a PR

**Comment by PatrickAlphaC** [comment]
Nice! Fixed
