### ISSUE TITLE
Missing QR codes for Lesson 12 challenge

### ISSUE THREAD

**Issue by npa528** [Cyfrin/foundry-full-course-f23#134]
### Lesson

Lesson 12

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://youtu.be/wUjYK5gwNZs?t=17213

### Describe the bug

In the end of Lesson 12 I don't see any QR codes for the usual challenge at the end of every Lesson. I thought that this was intentionally like this.

On the contrary, I found that there is a Challenge 12 on:
Sepolia: https://sepolia.etherscan.io/address/0xe5760847db2f10a74fc575b4803df5fe129811c1#code
Arbitrum: https://arbiscan.io/address/0x3dbbf2f9acfb9aac8e0b31563dd75a2d69148d64#code

So I understand that QR code is missing in the end of Lesson 12 and should be added in an update.

**Comment by PatrickAlphaC** [comment]
Thanks for this :) 

This one was intentionally not added hehe. This is where I wanted people to snoop out the challenge themselves!
