### ISSUE TITLE
Lesson 7 | Style Guide url has changed 

### ISSUE THREAD

**Issue by dew10120** [Cyfrin/foundry-full-course-f23#1359]
### Describe the enhancement

The given URL in the lesson is 
contracts/STYLE.md

The new URL is contracts/STYLE_GUIDE.md

**Comment by lguilhermef** [comment]
There's an open Pull Request for this, which you can check [here](https://github.com/Cyfrin/foundry-full-course-f23/pull/1215).
You can find the current URL for the Chainlink Style Guide [here](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/STYLE_GUIDE.md).

**Comment by PatrickAlphaC** [comment]
Done!
