### ISSUE TITLE
The files do not pushed to GitHub

### ISSUE THREAD

**Issue by Vodvalex** [Cyfrin/foundry-full-course-f23#1385]
Hi Everyone
I have been following exactly the video how to push files up to GitHub.Unfortunately after the command :
$ git push   -u origin main  and cheking the Code button and refresh there were no files in the repositiry.I have tryed twice with no avail.Is someone would be so kind to help me in pushing files up to gitHub.I use Gitpod .
Please see the attached
!
![20240206_222140](https://github.com/Cyfrin/foundry-full-course-f23/assets/135243775/990c2144-0860-473b-840d-cf8dbf394e7c)
Thank you.

**Comment by HemaDeviU** [comment]
First,Can you ensure that you have files staged for commit. You can do this by running `git status` in your Gitpod terminal. and then try `git add .`
`git commit -m "commit message"`

**Comment by Bharath-Anbazhagan** [comment]
Hi Buddy,

Is this Issue Solved? (or) still facing issues?

**Comment by PatrickAlphaC** [comment]
Going to close this, let us know if you're still having issues.
