### ISSUE TITLE
Issue with foundry in gitpod

### ISSUE THREAD

**Issue by Tusharkuma** [Cyfrin/foundry-full-course-f23#1399]
### Discussed in https://github.com/Cyfrin/foundry-full-course-f23/discussions/1397

<div type='discussions-op-text'>

<sup>Originally posted by **Tusharkuma** February 12, 2024</sup>
I'm using foundry in gitpod. Everytime i login to it to work where i left, I need to re-install foundry everytime. Else in any foundry command it show "command not found". Why foundry lost every time. What's needed so not to install it everytime. Does anyone have solution for it?
</div>

**Comment by ibanigabriel** [comment]
hi 

please my gitpod is not cloning the repo any help

**Comment by PatrickAlphaC** [comment]
Sorry on my delay. Which lesson are you having issues in GitPod with?

**Comment by ibanigabriel** [comment]
It was on foundry course  but i have handled  it thanks for your  concern
