### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by aliweb3** [Cyfrin/foundry-full-course-f23#144]
hi i have issu whith this command in my terminal
```
forge create SimpleStorage --rpc-url http://127.0.0.1:7545
 --interactive
 ```
 when i want to run this command i got this error:
 
 ```
 forge create SimpleStorage --rpc-url http://127.0.0.1:7545
 --interactive
[⠢] Compiling...
[⠆] Compiling 1 files with 0.8.19
[⠰] Solc 0.8.19 finished in 81.31ms
Compiler run successful!
Error: 
Error accessing local wallet. Did you set a private key, mnemonic or keystore?
Run `cast send --help` or `forge create --help` and use the corresponding CLI
flag to set your key via:
--private-key, --mnemonic-path, --aws, --interactive, --trezor or --ledger.
Alternatively, if you're using a local node with unlocked accounts,
use the --unlocked flag and either set the `ETH_FROM` environment variable to the address
of the unlocked account you want to use, or provide the --from flag with the address directly.
zsh: command not found: --interactive
```
how can i fix this? please help

**Comment by DevSwayam** [comment]
Did You make sure that your Loal blockchain was running parallely on another terminal?

**Comment by aliweb3** [comment]
Yes, in anvil is working , but in ganache have problem

**Comment by ChefAharoni** [comment]
Looks like there's a problem with your private key.

Are you sure you've pasted it correctly?
You should click on the key button here - 
<img width="1200" alt="image" src="https://github.com/Cyfrin/foundry-full-course-f23/assets/4399057/7c4a9a04-df42-410b-903a-89ef4a645a47">

And copy the private key (the second option) - that's the key you paste into the terminal.

**Comment by alucero1993** [comment]
Hi Guys! New here and excited to become a great contributor to this new cryptographic world :D

**Comment by PatrickAlphaC** [comment]
Closing this as it's a stale isssue. For questions, please use the discussions!
