### ISSUE TITLE
Chapter 7 No link for Brownie Smart Contract Github Repo.

### ISSUE THREAD

**Issue by DevSwayam** [Cyfrin/foundry-full-course-f23#151]
### Describe the enhancement

So on the Readme File for chapter 7 the link to chainking brownie Contract is not present would like to add that link in Readme.md file.  

It will be used to import contracts.

timestamp for refernce https://youtu.be/sas02qSFZ74?t=467

**Comment by PatrickAlphaC** [comment]
Fixed!

https://github.com/Cyfrin/foundry-full-course-f23/commit/9d7360bcfbc68aaf96eb8082619afd7877c5036c
