### ISSUE TITLE
Lesson 12 -> Handler.t.sol (Video clip is not there on the Cyfrin Updarft)

### ISSUE THREAD

**Issue by gopalchandak-dev** [Cyfrin/foundry-full-course-f23#1515]
### Lesson

Lesson 12

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://youtu.be/wUjYK5gwNZs?t=13653

### Describe the bug

"Handler.t.sol" fuzz file is not available in the Cyfrin Updraft...
--> Advanced Foundry --> Section 3 --> 19. Create the fuzz test handler pt2... --> _________MISSING handler.t.sol_____ --> modification in handler function
This part of clip is not available.

![Screenshot 2024-03-22 203328](https://github.com/Cyfrin/foundry-full-course-f23/assets/141278896/fb34fe35-f1db-4afd-8db0-90797deceef0)
 

Btw, course is wonderful, thanks Man.

**Comment by PatrickAlphaC** [comment]
@cromewar could you take a look?

**Comment by AGMASO** [comment]
Same issue, still there

**Comment by PatrickAlphaC** [comment]
This should be fixed now
