### ISSUE TITLE
 compilation skipped memory allocation of 2952790016 bytes failed

### ISSUE THREAD

**Issue by arunkumard001** [Cyfrin/foundry-full-course-f23#1623]
### Lesson

Lesson 8

### Operating System

Windows

### Describe the bug

when i am trying to forked test environment and dynamic private keys/test:
i am facing a error called
forge test --fork-url $Sepolia_rpc_url -vvvvv
[⠊] Compiling...
No files changed, compilation skipped
memory allocation of 2952790016 bytes failed

so I try to increase the memory limit in .toml file but I encounter the same error , can you help me to solve?
but i can able to forge build and forge compile with error

**Comment by PatrickAlphaC** [comment]
Why are you doing a fork test for lesson 8?

What repo are you running this test on?
