### ISSUE TITLE
Defi protocol - Lesson 14: Setup liquidations 

### ISSUE THREAD

**Issue by whxint** [Cyfrin/foundry-full-course-f23#1657]
### Lesson

Lesson 14

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://youtu.be/8dRAd-Bzc_E?t=10229

### Operating System

macOS (Apple Silicon)

### Describe the bug

Liquidator pays someone's debt and burns its own DSC, but its state in the engine contract does not change.

When the burn() function runs, the liquidated user's DSC amount decreases, but the liquidater's tokens are transferred to the contract and burned. Considering that the liquidater has a DSC of $100 dollars, it does not have any DSCs since they are all burned, but it continues to write $100 dollars in the s_DSCMinted variable of the contract. When liquidater comes later and mints $100, he will write $200 in the s_DSCMinted variable, but he will have $100 dollars. It always has extra DSC.

```
function liquidate(
        address collateral,
        address user,
        uint256 debtToCover
    )
        external
        moreThanZero(debtToCover)
        nonReentrant
    {
        uint256 startingUserHealthFactor = _healthFactor(user);
        if (startingUserHealthFactor >= MIN_HEALTH_FACTOR) {
            revert DSCEngine__HealthFactorOk();
        }
        // If covering 100 DSC, we need to $100 of collateral
        uint256 tokenAmountFromDebtCovered = getTokenAmountFromUsd(collateral, debtToCover);
        // And give them a 10% bonus
        // So we are giving the liquidator $110 of WETH for 100 DSC
        // We should implement a feature to liquidate in the event the protocol is insolvent
        // And sweep extra amounts into a treasury
        uint256 bonusCollateral = (tokenAmountFromDebtCovered * LIQUIDATION_BONUS) / LIQUIDATION_PRECISION;
        // Burn DSC equal to debtToCover
        // Figure out how much collateral to recover based on how much burnt
        _redeemCollateral(collateral, tokenAmountFromDebtCovered + bonusCollateral, user, msg.sender);
        _burnDsc(debtToCover, user, msg.sender);

        uint256 endingUserHealthFactor = _healthFactor(user);
        // This conditional should never hit, but just in case
        if (endingUserHealthFactor <= startingUserHealthFactor) {
            revert DSCEngine__HealthFactorNotImproved();
        }
        revertIfHealthFactorIsBroken(msg.sender);
    }
```

If the liquidator liquidates a user, the DSC that will be used is not what he pressed into the engine, but a DSC sent to him by someone else or perhaps purchased from the exchange. Therefore, when liquidating a user, their DSC balance will not decrease. But when the Liquidator performs DepositColleteral and liquidates someone, he always has an extra amount of DSC. If he wants to withdraw his collectral after liquidating someone, the application will give an error because he does not have such a DSC amount, but the DSC engine shows that he has it. Why is the liquidator's DSC balance not taken into account in DSCEngine after a successful liquidation call?

**Comment by whxint** [comment]
```
function _burnDsc(uint256 amountDscToBurn, address onBehalfOf, address dscFrom) private {
        s_DSCMinted[onBehalfOf] -= amountDscToBurn;

        bool success = i_dsc.transferFrom(dscFrom, address(this), amountDscToBurn);
        // This conditional is hypothetically unreachable
        if (!success) {
            revert DSCEngine__TransferFailed();
        }
        i_dsc.burn(amountDscToBurn);
    }
```
When the burn() function runs, the liquidated user's DSC amount decreases, but the liquidater's tokens are transferred to the contract and burned. Considering that the liquidater has a DSC of $100 dollars, it does not have any DSCs since they are all burned, but it continues to write $100 dollars in the s_DSCMinted variable of the contract. 

Someone is making depositcollateral, the system will run into a bug. It might have been overlooked because it wasn't a real project, or it might have worked that way. $100 dollars in the s_DSCMinted variable of the contract. When liquidater comes later and mints $100, he will write $200 in the s_DSCMinted variable, but he will have $100 dollars. It always has extra DSC.

**Comment by Chinwuba22** [comment]
Ok now I get you. I can see `address(this)`, would take a look at the code better soon. However, the aim of this teaching was specifically to teach and the code also went through an audit process after this I'm sure that would have been spoted.

**Comment by Chinwuba22** [comment]
Sorry @whxint, Yes it isnt a real project amd was intented to help team more how to write.

I think i get your question however and it is not a bug; the `s_DSCMinted` is also updated in the `_burnDsc` function here: ` s_DSCMinted[onBehalfOf] -= amountDscToBurn;` which would mean that that the person to be liquidated balance is updated correctly.

**Comment by cromewar** [comment]
Thanks for the answer @Chinwuba22

**Comment by whxint** [comment]
No. liquidatior balance never decreases. The state in the DSC engine never changes.

**Comment by Chinwuba22** [comment]
https://github.com/Cyfrin/foundry-defi-stablecoin-f23/blob/main/test/unit/DSCEngineTest.t.sol#L453C5-L460C6

**Comment by whxint** [comment]
Bro, I am responding based on your answer. You go and test the increase in the amount of weth collateral. Is this a joke ? 

`s_DSCMinted[onBehalfOf] -= amountDscToBurn;`

This does not reduce the DSC balance of the liquidatior and then DSC is transferred to the contract and burned, but the contract state does not change. Understand the code well pls

**Comment by Chinwuba22** [comment]
Send your own test that is failing here.
