### ISSUE TITLE
Nft showing blank image

### ISSUE THREAD

**Issue by Okhayeeli** [Cyfrin/foundry-full-course-f23#1678]
Good day Cyfrin updraft, thank you so much for my journey so far. My issue is with deploying my nft, at first I deployed but the image was blank so, I deleted it and tried to correct the moodnft svg url cause the previous one seemed to be incorrect, however when I wanted to import the nft it said id error, so, i decided to use a different account and use a different make deploy( make deployMood1) this changed the address and I imported it into the new account at first it gave same errors, it eventually worked but gave me the same blank photo

![Uploading Screenshot 2024-05-03 173502.png…](https://uploads.linear.app/cadb8f73-539c-468d-a480-57bfa3b91783/40d963fa-b91c-4e58-a6e6-7bb09adf3f34/21f03ed9-0c8c-47d6-82c4-9119f1d02e04?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhZGI4ZjczLTUzOWMtNDY4ZC1hNDgwLTU3YmZhM2I5MTc4My80MGQ5NjNmYS1iOTFjLTRlNTgtYTZlNi03YmIwOWFkZjNmMzQvMjFmMDNlZDktMGM4Yy00N2Q2LTgyYzQtOTExOWYxZDAyZTA0IiwiaWF0IjoxNzE0NzU0ODY4LCJleHAiOjMzMjg1MzE0ODY4fQ.mo78nw9duWMJix9fEJyrHRu-1-2YKW4C6-E2Fph-oIY)

**Comment by PatrickAlphaC** [comment]
https://github.com/Cyfrin/foundry-nft-f23/issues/29
