### ISSUE TITLE
forge test -m should be corrected to -mt or --match-test

### ISSUE THREAD

**Issue by RichardPalladino** [Cyfrin/foundry-full-course-f23#174]
### Lesson

Lesson 6

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://youtu.be/sas02qSFZ74?t=1640

### Describe the bug

Others have been using -mt and I have been using --match-test ... May want to inject a quick blurb in the video that it's now -mt for "match test".

**Comment by PatrickAlphaC** [comment]
Thanks! We've added this to the chronological updates section already. 

https://github.com/Cyfrin/foundry-full-course-f23/blob/main/chronological-updates.md#lesson-6
