### ISSUE TITLE
Modulo examples error

### ISSUE THREAD

**Issue by ahop1** [Cyfrin/foundry-full-course-f23#263]
### Lesson

Lesson 9

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://youtu.be/sas02qSFZ74?t=14685

### Describe the bug

Love the videos, they have been very helpful. Just noticed a minor error when explaining modulo which might trip someone up if they haven't come across it before. Examples shown on remix in the demo are the wrong way around.

It shows on screen (line 11):
```
// 2 % 2 = 0. 2 % 3 = 1.      2 % 6 = 0.  2 % 7 = 1
```
What it should be:
```
// 2 % 2 = 0. 3 % 2 = 1.      6 % 2 = 0.  7 % 2 = 1
```

**Comment by PatrickAlphaC** [comment]
ah... crap. Thank you. 

Fixed here!

https://github.com/Cyfrin/foundry-full-course-f23/blob/main/chronological-updates.md#lesson-9
