### ISSUE TITLE
lesson:11 Can't Mint with ```make``` after deploying

### ISSUE THREAD

**Issue by highHumann** [Cyfrin/foundry-full-course-f23#404]
```
mint:
	@forge script script/Interactions.s.sol:MintBasicNft $(NETWORK_ARGS)
```
 i was using this where 
```
ifeq ($(findstring --network sepolia,$(ARGS)),--network sepolia)
NETWORK_ARGS := --rpc-url $(SEPOLIA_RPC_URL) --private-key $(PRIVATE_KEY) --broadcast --verify --etherscan-api-key $(ETHERSCAN_API_KEY) -vvvv
endif
```
 but I was still getting an error 
while running it maunally without using ```make mint``` in the terminal it succeeded don't know why it was not working with ```make```

_Originally posted by @highHumann in https://github.com/Cyfrin/foundry-full-course-f23/discussions/402#discussioncomment-6515499_

**Comment by txusif** [comment]
How did you run it?

**Comment by PatrickAlphaC** [comment]
Can you make this in discussions?

**Comment by highHumann** [comment]
https://github.com/Cyfrin/foundry-full-course-f23/discussions/465#discussion-5444893 I have created a discussion here

**Comment by highHumann** [comment]
> How did you run it?

``` make mint ARGS="--network-sepolia"```

**Comment by highHumann** [comment]
it finally worked i found my error I was writing make mint ```ARGS="--network-sepolia"``` when I should write ```make mint ARGS="--network sepolia"```
