### ISSUE TITLE
Lesson 6, we can use interactive when we are running scripts

### ISSUE THREAD

**Issue by Kaiziron** [Cyfrin/foundry-full-course-f23#422]
### Lesson

Lesson 6

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://www.youtube.com/watch?v=umepbfKp5rI&t=27765s

### Describe the bug

We can use interactive to enter private key when we are running scripts, instead of `--interactive`/`-i`, we can use `--interactives <num>`/`-i <num>`, and specify the sender address with `--sender`

For example :
```
forge script script/DeploySimpleStorage.s.sol --rpc-url http://127.0.0.1:8545 --broadcast --sender 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 -i 1
```

**Comment by PatrickAlphaC** [comment]
Nice! Can you add this to discussions instead of as an issue?

**Comment by Kaiziron** [comment]
Sure
