### ISSUE TITLE
Constructor of "VRFV2WrapperConsumerBase.sol" has 2 arguments instead of 1

### ISSUE THREAD

**Issue by Ciphadus7** [Cyfrin/foundry-full-course-f23#453]
In the video, the constructor takes a single argument: address _vrfCoordinator.
In the updated code of VRFV2WrapperConsumerBase.sol, it takes two.
Namely:
`  constructor(address _link, address _vrfV2Wrapper) {
    LINK = LinkTokenInterface(_link);
    VRF_V2_WRAPPER = VRFV2WrapperInterface(_vrfV2Wrapper);
  }`
  
Stuck at this point.
Confused as to what it needs as the second argument.

**Comment by PatrickAlphaC** [comment]
Can you go to discussions instead of issues?
