### ISSUE TITLE
could not install foundry.

### ISSUE THREAD

**Issue by nagrarohit** [Cyfrin/foundry-full-course-f23#509]
![Screenshot 2023-08-01 211005](https://github.com/Cyfrin/foundry-full-course-f23/assets/121886772/4700c7cb-ebdc-439a-8bfd-bd86577c3904)
I have tried most of the methods mentioned in the discussions tab. But at the end i got the same output. so i have to open the issue. if any one have  a sloution then please discuss , it will be very helpful.

**Comment by theirrationalone** [comment]
First execute this 👇 command:
```terminal
export http_proxy=http://127.0.0.1:7890 https_proxy=http://127.0.0.1:7890
```

after executing 👆 command, now try reinstall foundry.

**Comment by nagrarohit** [comment]
Thanks @theirrationalone  but, Still it is showing the same error.

**Comment by theirrationalone** [comment]
> Thanks @theirrationalone  but, Still it is showing the same error.

Not working 😧, It's silly to ask 😅, but be make sure you have an internet connection.

**Comment by theirrationalone** [comment]
Hey i got one resource, You can follow this.... 

[Follow this](https://www.google.com/amp/s/www.debugpoint.com/failed-connect-raw-githubusercontent-com-port-443/%3famp=1)

**Comment by nagrarohit** [comment]
thanks a lot dear @theirrationalone . installation done succefully.

**Comment by nagrarohit** [comment]
> Welcome to the Blockchain Development with foundry @nagrarohit !
credits to you brother @theirrationalone
