### ISSUE TITLE
Link in Lesson 1 not working: Error 406

### ISSUE THREAD

**Issue by vivekup3424** [Cyfrin/foundry-full-course-f23#740]
### Describe the enhancement

When going to ```chain.link/education/defi``` link in Lesson1 section = `     

What have Smart Contracts done so far?` . It is showing that the link is bad, that is its showing error 406. Maybe you can update the link, or I can do so.

**Comment by PatrickAlphaC** [comment]
oo. We will probably need to update the link. Can you make a PR perhaps?

**Comment by Ethanol48** [comment]
It seems fine now https://chain.link/education/defi, maybe was a temporary error in chainlink's part.
