### ISSUE TITLE
4-Lesson.sol Challenge | Line 40 Typo

### ISSUE THREAD

**Issue by roman-vasi1enko** [Cyfrin/foundry-full-course-f23#780]
### Lesson

Lesson 4

### Operating System

None

### Describe the bug

Line 40 of the 4-Lesson.sol challenge code contains a typo in the "10e10" number:
`actualPrice = actualPrice * 10e10;`

Should be "1e10":
`actualPrice = actualPrice * 1e10;`

**To pass the challenge**, add an extra zero to your answer. 
For examlpe, if getPrice() returns:
1637320000000000000000, you need to paste this number plus 0, like this:
16373200000000000000000

**Comment by roman-vasi1enko** [comment]
Contract URL: https://sepolia.etherscan.io/address/0x1b30DA2a868704483143A4D46865Ac9585629fd0#code

**Comment by cromewar** [comment]
Yes ser you are right, adding this to the chronological updates and also to the next video, thanks @roman-vasi1enko
