### ISSUE TITLE
It would be better if the Readme file contains direct link to Link Token Contract.

### ISSUE THREAD

**Issue by DevSwayam** [Cyfrin/foundry-full-course-f23#862]
### Describe the enhancement
I was going through readme file In lesson 9 in which we deploy our own Link Token contract for anvil chain ht direct link to the contract was not there. It would be better if its included in the readme file with the time stamp.

![image](https://github.com/Cyfrin/foundry-full-course-f23/assets/99035115/b428a426-483e-449a-8820-45ab922a4e13)

### Video TimeStamp
<a href="https://www.youtube.com/watch?v=sas02qSFZ74&t=19957s">Link</a>

### Github Repo Link that i would like to add 
<a href="https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/blob/main/test/mocks/LinkToken.sol">Link</a>

### Also the Command to install the solmate package
```forge install transmissions11/solmate --no-commit```

**Comment by cromewar** [comment]
Can you make a pr for this please?

**Comment by PatrickAlphaC** [comment]
Fixed in [233499f](https://github.com/Cyfrin/foundry-full-course-f23/commit/233499f11d9892b405b63354e0e04c35f3040d21)
