### ISSUE TITLE
Lesson 6 Foundry installation error

### ISSUE THREAD

**Issue by Zatin010** [Cyfrin/foundry-full-course-f23#876]
"Seems like Windows and Ubuntu WSL have different opinions on 'forge --version'. On Windows, it's all 'I got this,' but in WSL, it's like 'What command?'. 🙄 Any tips for syncing up these two worlds or should I just stick to the 'normal' terminal in VS Code? 🤔

**Comment by Ethanol48** [comment]
I don't have much experience in windows, but I have a machine that I used with WSL, some programs didn't worked in WSL if I install them in windows and vice-versa, I think there are different 'machines' as there are isolated, ubuntu can't run windows executables and windows can't run linux's ones, it's normal.

Try to install foundryup in a WSL command-line

If I'm not mistaken there's some difference when installing it in WSL but it won't be that much of a difference

**Comment by Zatin010** [comment]
I tried installing foundryup the WSL way but its not letting me install even after installing rust. I am just using the PowerShell terminal as that's only working for me RN. Thanks for the response.

**Comment by SilviyaPBrayanova** [comment]
Hi guys. I tried WSL on Windows and everything installs and works in general. When I reached the integration of the foundry tools (anvil) with the Thirdweb tool, all fell apart. So I switched to GitBash and haven't had any further issues.

**Comment by Zatin010** [comment]
Got it Silviya.

**Comment by cromewar** [comment]
@Zatin010 Please use [Windows Terminal](https://apps.microsoft.com/detail/windows-terminal/9N0DX20HK701?hl=en-us&gl=EC) on the "+" button you will have the linux instance, install everything through it.

Fot Vscode to take the terminal as the linux one you have 2 options:

1. Open vscode from the windows terminal (linux instance) with `code .`. 
2. Open a new instance directly on vscode using the left button for WSL.

> Do not forget to have the remote development dependencies installed.

Cheers.

**Comment by karthiksathishjeemain** [comment]
Any Idea on SSL Verification Error? I suffered a lot at this error, so I switched to gitpod. But as it has some time restrictions, I am no longer able to use it. So thinking back of working in the local environment. Btw I am using WSL on my Windows system
![Screenshot 2023-09-20 124316](https://github.com/Cyfrin/foundry-full-course-f23/assets/115690993/eb8b5f58-5243-4f32-afda-b60c8bb8dea2)

**Comment by cromewar** [comment]
Does [this](https://stackoverflow.com/questions/49012543/how-to-disable-curl-ssl-certificate-verification) help you @karthiksathishjeemain?

**Comment by GTK-ARJUN** [comment]
WSL is like an isolated OS within your PC. you have to install forge separately on WSL and then use it. if you use it on Windows, install Rust from the official website.

**Comment by karthiksathishjeemain** [comment]
> Does [this](https://stackoverflow.com/questions/49012543/how-to-disable-curl-ssl-certificate-verification) help you @karthiksathishjeemain?

![image](https://github.com/Cyfrin/foundry-full-course-f23/assets/115690993/6073b892-2c96-4ed7-8fe7-704a89f609fa)

The problem still exists (even after using -k command after curl)
