### ISSUE TITLE
forge test -m flag is deprecated

### ISSUE THREAD

**Issue by padamson** [Cyfrin/foundry-full-course-f23#908]
### Lesson

Lesson 7

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://youtu.be/sas02qSFZ74?list=PL4Rj_WH6yLgWe7TxankiqkrkVKXIwOP42&t=1649

### Describe the bug

The `-m regex` option to `forge test` is deprecated. See `--match-test`.

**Comment by shrutic11** [comment]
--match-test OR --mt works instead

**Comment by cromewar** [comment]
This will be added to the next video with the updates 😉 thanks @padamson
